# Generated by Django 4.0.4 on 2022-04-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',)},
        ),
    ]
